import type { Metadata } from 'next';
import AuthSession from '@/(route)/authSession';
import ToastContainer from '@/components/toast';
import '@styles/global.css';
import MSWComponent from '@/mokes/MSWComponent';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
    return (
        <html lang="ko">
            <body>
                <MSWComponent>
                    <ToastContainer />
                    <AuthSession>
                        <main>{children}</main>
                    </AuthSession>
                </MSWComponent>
            </body>
        </html>
    );
};

export default RootLayout;
