import type { Metadata } from 'next';
import AuthSession from '@/(Route)/authSession';
import ToastContainer from '@Component/Common/Toast';
import '@Style/global.css';
import MSWComponent from '@/Mokes/MSWComponent';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
    return (
        <html lang="ko">
            <body>
                <MSWComponent>
                    <ToastContainer />
                    <AuthSession>
                        <main>{children}</main>
                    </AuthSession>
                </MSWComponent>
            </body>
        </html>
    );
};

export default RootLayout;
