import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const LoginLayout = async ({ children }: Readonly<{ children: React.ReactNode }>) => {
    return <>{children}</>;
};

export default LoginLayout;
